### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by swamidass** [ntamas/yard#8]

**Comment by ntamas** [comment]
I am not working in research actively any more, so the project is in maintenance stage - I am willing to fix bugs but it's unlikely that there will be any more new features in the near future.

**Comment by swamidass** [comment]
So I'm the author of the original CROC study. I was considering writing another release of the software with some important new features. I discovered that some (but not all of them) are in yard. So, I was curious if you any of you would be interested in participating in this project.

**Comment by ntamas** [comment]
Thanks for your consideration (and sorry for the late response - I was on the road last week) - unfortunately I don't have too much spare time nowadays to dedicate to my hobby projects and I don't want to hold you back - so feel free to take anything that you need from `yard` and I'll also be happy to answer any questions, but unfortunately I cannot promise anything more than this.

**Comment by svidela** [comment]
Hi there, 

I'm out of research (and software development) for the moment. Good luck!
